paths:
  card_fasta: "/data/aidannguyen/amr-soft-prompting/data/raw/protein_fasta_protein_homolog_model.fasta"
  card_json: "/data/aidannguyen/amr-soft-prompting/data/raw/card.json"
  aro_index: "/data/aidannguyen/amr-soft-prompting/data/raw/aro_index.tsv"
  output_dir: "/data/aidannguyen/amr-soft-prompting/outputs/"

